# This is an example based in Java. You can change it to the language/runtime you are using
# If you want more info on how to setup this Dronefile, please check https://guidelines.quintoandar.com.br/#/drone/?id=dronefile

clone:
  clone:
    image: plugins/git
    depth: 20

pipeline:
    assemble:
      image: openjdk:11
      commands:
        - ./gradlew clean assemble
      when:
        event: push

    check:
      image: openjdk:11
      commands:
        - ./gradlew check -x test
      when:
        event: push

    allTests:
      image: openjdk:11
      commands:
        - ./gradlew test jacocoTestCoverageVerification
      when:
        event: push

    publish:
      image: quintoandar/drone-gcr
      pull: true
      repo: quintohub/empty-template
      dockerfile: empty-template.forno.Dockerfile
      tag: [ '${DRONE_BRANCH}-${DRONE_COMMIT:0:7}', '${DRONE_BRANCH}-latest' ]
      when:
        event: push
        branch: [ forno ]

    # This configuration below is part of the required configurations to deploy an
    # application on our infrastructure, but NOT THE ONLY ONE.
    # See more details at https://www.notion.so/productquintoandar/Deployment-System-5af39a6f15d040229cc90e2416955726.
    forno-deploy:
      image: gcr.io/quintohub/drone-deploy
      pull: true
      deployment:
        # The application name below MUST be present on the 'applications' list
        # in the .checklist.yaml file.
        # (Checklist content is server-side refreshed only when merged to master,
        # so make sure this has been done before trying to deploy.)
        # Its value must be unique amongst all applications (the full list can be
        # viewed at Backstage.)
        application: empty-template
        environment: forno
        # These parameters are interpoled in runtime by Drone and merged to static
        # parameters from files.
        parameters:
          tag: '${DRONE_BRANCH}-${DRONE_COMMIT:0:7}'
        parameters_from_files:
          - kube/forno/parameters.yaml
      when:
        event: push
        branch:
          - forno
