# These parameters are forwarded to our Deployment API, so the full application
# specification can be assembled, based on the content of the Deployment Monorepo.
# This additional content, which completes the deployment example, is at
# https://github.com/quintoandar/deployments/tree/master/templates/empty-template
#
# See more details about ou Deployment Architecture at
# https://www.notion.so/productquintoandar/Deployment-System-5af39a6f15d040229cc90e2416955726.

port: 8080

env:
  FOO: BAR
  FOO2: BAR2

# For more details about how to use secrets on our infrastructure, see
# https://www.notion.so/productquintoandar/Vault-035a8398eb3a448096ddf99636f60099
# secrets:
#   FOOBAR_TOKEN: kv/data/apps/foobar/token#value
#   DB_FOOBAR_USERNAME: "database/creds/forno-readonly-foobar#username"
#   DB_FOOBAR_PASSWORD: "database/creds/forno-readonly-foobar#password"

# If using secrets, Docker command needs to be explicitly declared. This is just
# and example, commands may highly vary depending on language and frameworks being
# used.
# cmd:
# - /bin/entrypoint.sh

readinessProbePath: /actuator/health
livenessProbePath:  /actuator/health
